package com.C2ManuKevin.juego.vista;

import com.C2ManuKevin.juego.controlador.MesaDeJuegoController;
import com.C2ManuKevin.juego.modelo.Jugador;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author KevinRG & Manu
 */
public class MesaDeJuego extends javax.swing.JFrame {

    MesaDeJuegoController controller;

    /**
     * Creates new form MesaDeJuego
     *
     * @param controller
     */
    public MesaDeJuego(MesaDeJuegoController controller) {
        initComponents();
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jug1TablLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        manoPanel = new javax.swing.JPanel();
        cartaMesaPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        sayUNO = new javax.swing.JButton();
        nuevaCarta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        Jug1TablLabel.setText("________");

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("PLAYERS");

        javax.swing.GroupLayout manoPanelLayout = new javax.swing.GroupLayout(manoPanel);
        manoPanel.setLayout(manoPanelLayout);
        manoPanelLayout.setHorizontalGroup(
            manoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
        );
        manoPanelLayout.setVerticalGroup(
            manoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(manoPanel);

        javax.swing.GroupLayout cartaMesaPanelLayout = new javax.swing.GroupLayout(cartaMesaPanel);
        cartaMesaPanel.setLayout(cartaMesaPanelLayout);
        cartaMesaPanelLayout.setHorizontalGroup(
            cartaMesaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );
        cartaMesaPanelLayout.setVerticalGroup(
            cartaMesaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        logArea.setEditable(false);
        logArea.setColumns(20);
        logArea.setRows(5);
        jScrollPane3.setViewportView(logArea);

        sayUNO.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        sayUNO.setText("UNO!");
        sayUNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sayUNOActionPerformed(evt);
            }
        });

        nuevaCarta.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nuevaCarta.setText("Toma una carta");
        nuevaCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaCartaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nuevaCarta, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(sayUNO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cartaMesaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(Jug1TablLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cartaMesaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(sayUNO, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nuevaCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Jug1TablLabel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaCartaActionPerformed
        controller.getNuevaCarta();
        manoPanel.updateUI();
    }//GEN-LAST:event_nuevaCartaActionPerformed
    
    private void sayUNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sayUNOActionPerformed
        controller.decirUNO();
        
    }//GEN-LAST:event_sayUNOActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jug1TablLabel;
    private javax.swing.JPanel cartaMesaPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea logArea;
    private javax.swing.JPanel manoPanel;
    private javax.swing.JButton nuevaCarta;
    private javax.swing.JButton sayUNO;
    // End of variables declaration//GEN-END:variables

    public void showMano(List<JLabel> jTextAreas) {
        manoPanel.setLayout(new FlowLayout());
        manoPanel.removeAll();
        for (JLabel area : jTextAreas) {
            JPanel panel = new JPanel(new BorderLayout());
            panel.add(area, BorderLayout.CENTER);
            manoPanel.add(panel);
        }
        manoPanel.updateUI();
    }
    
    public void showJugadoresLista(List<JLabel> jLabels) {
        
        jPanel1.removeAll();
        for (JLabel jLabel : jLabels) {
            jPanel1.add(jLabel);
        }
        jPanel1.updateUI();
    }
    
    public void showCarta(JLabel jLabel) {
        cartaMesaPanel.setLayout(new FlowLayout());
        cartaMesaPanel.removeAll();
        cartaMesaPanel.add(jLabel);
        cartaMesaPanel.updateUI();
    }
    
    public void setJugadorNombre(Jugador jugador) {
        Jug1TablLabel.setText(jugador.toString());
    }
    
    public void setButtonEnable(Boolean b) {
        nuevaCarta.setEnabled(b);
        sayUNO.setEnabled(b);
    }
    
    public void reload() {
        manoPanel.updateUI();
        cartaMesaPanel.updateUI();
        jPanel1.updateUI();
        repaint();
    }
    
    public void setLog(String sr) {
        logArea.setText(logArea.getText() + "\n" + sr);
    }
}
